imports:
    - { resource: ../config.yml }
    - { resource: security.yml }
    - { resource: ../widgets.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/admin/routing.yml"
        strict_requirements: ~
    session:
        save_path: "%kernel.cache_dir%/../../sessions/admin/%kernel.environment%"

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    bundles:        [ ClientWebsiteBundle ]

# Doctrine Configuration
doctrine:
    orm:
        dql:
            string_functions:
                CAST: Sulu\Component\Rest\DQL\Cast

# SULU Content Configuration
sulu_content:
    preview:
        mode: auto
        websocket: false
        delay: 200

# SULU Admin Configuration
sulu_admin:
    name: %sulu_admin.name%
    email: %sulu_admin.email%

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
parameters:
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

sulu_contact:
    form_of_address:
        male:
            id: 0
            name: male
            translation: contact.contacts.formOfAddress.male
        female:
            id: 1
            name: female
            translation: contact.contacts.formOfAddress.female

# Massive Build Configuration
massive_build:
    targets:
        prod:
            dependencies:
                database: ~
                phpcr: ~
                fixtures: ~
                phpcr_migrations: ~
        dev:
            dependencies:
                database: ~
                fixtures: ~
                phpcr: ~
                user: ~
                phpcr_migrations: ~
        maintain:
            dependencies:
                node_order:
                search_index:
                phpcr_migrations: ~

